config/routes.rb
#---
# Excerpted from "Deploying with JRuby",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material, 
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose. 
# Visit http://www.pragmaticprogrammer.com/titles/jkdepj for more book information.
#---
Twitalytics::Application.routes.draw do
  get "customers/index", :as => :customers

  get "company/index", :as => :company

  post "company/update", :as => :company_status

  get "dashboard/index"

  post "customers/retweet/:id", :controller => :customers, :action => :retweet, :as => :retweet

  root :to => "dashboard#index"
end

app/models/analytics.rb
#---
# Excerpted from "Deploying with JRuby",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material, 
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose. 
# Visit http://www.pragmaticprogrammer.com/titles/jkdepj for more book information.
#---
class Analytics < ActiveRecord::Base

  def self.refresh(statuses)
    before = statuses.map(&:created_at).max
    statuses = Status.where('created_at < ?', before).order("created_at desc").limit(200)
    Analytics.create(
      :positivity_followers_r => calc_positivity_followers_r(statuses),
      :positivity_stdv => calc_positivity_stdv(statuses)
    )
  end

  protected

  def self.calc_positivity_followers_r(statuses)
    x = statuses.map(&:positivity_score)
    y = statuses.map(&:followers_count)
    AnalyticsUtil.pearson_r(x, y)
  end

  def self.calc_positivity_stdv(statuses)
    scores = statuses.map(&:positivity_score)
    AnalyticsUtil.standard_dev(scores)
  end
end

app/models/status.rb
#---
# Excerpted from "Deploying with JRuby",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material, 
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose. 
# Visit http://www.pragmaticprogrammer.com/titles/jkdepj for more book information.
#---
class Status < ActiveRecord::Base
  extend TorqueBox::Injectors

  always_background :retweet

  def self.find_or_create_from(tweets)
    r = tweets.map do |tweet|
      existing = Status.where(:remote_id => tweet.id.to_s).first
      begin
        existing.nil? ?
            Status.create(
              :created_at => tweet.created_at,
              :status_text => tweet.text,
              :creator => tweet.from_user,
              :remote_id => tweet.id.to_s
            ) :
            existing
      rescue => e
        # probably some bad characters in the tweet
        nil
      end
    end.compact

    topic.publish r.to_json
    r
  end

  def self.topic
    @@topic ||= inject('/topics/statuses')
  end

  def retweet
    sleep(10)
    # Twitter.update("RT @#{creator}: {status_text}")
    puts "Retweeting Status{id=#{id}}"
  end
  
  def preprocess!
    set_positivity_score!
    set_followers_count!
    self.save
  end

  def positivity_score
    read_attribute(:positivity_score) || 0
  end

  def followers_count
    read_attribute(:followers_count) || 0
  end

  private

  def set_positivity_score!
    # some simple parsing to determine if the tweet is positive or negative
    score = 0
    self.status_text.scan(/happy|great|love/).each { score += 1 }
    self.status_text.scan(/hate|bad|angry/).each { score -= 1 }
    self.status_text.scan(/:\)/).each { score += 5 }
    self.status_text.scan(/:\(/).each { score -= 5 }
    self.status_text.scan(/#ftw/).each { score += 15 }
    self.status_text.scan(/#fail/).each { score -= 15 }
    self.status_text.scan(/!/).each { score *= 2 }
    write_attribute(:positivity_score, score)
  end

  def set_followers_count!
    # any way we try to do this without an OAuth token will cause us to exceed our rate-limit very quickly
    # user = Twitter.user(creator)
    # write_attribute(:followers_count, user ? user.followers_count : 0)
    if read_attribute(:followers_count).nil?
      write_attribute(:followers_count, rand(1000))
    end
  rescue
    # we probably exceeded our Twitter rate-limit :(
    write_attribute(:followers_count, 0)
  end
end

app/controllers/application_controller.rb
#---
# Excerpted from "Deploying with JRuby",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material, 
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose. 
# Visit http://www.pragmaticprogrammer.com/titles/jkdepj for more book information.
#---
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/company_controller.rb
#---
# Excerpted from "Deploying with JRuby",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material, 
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose. 
# Visit http://www.pragmaticprogrammer.com/titles/jkdepj for more book information.
#---
class CompanyController < ApplicationController
  include TwitterUtil
  extend GetBack::JoJo

  def index
    with_twitter_account do |username|
      @username = username
      @statuses = (Twitter.user_timeline(username, :count => 20)).map do |status|
        {:created_at => status.created_at, :status_text => status.text}
      end
    end
  end

  def update
    post_update(params[:status_text])
    
    flash[:notice] = "Status updated!"
    redirect_to company_path
  end

  private

  def post_update(text)
    # We won't actually update because that requires an OAuth token.
    # Twitter.update(text)
    sleep 10
    puts "update posted successfully"
  end

  get_back :post_update, :pool => 10
end

app/controllers/customers_controller.rb
#---
# Excerpted from "Deploying with JRuby",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material, 
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose. 
# Visit http://www.pragmaticprogrammer.com/titles/jkdepj for more book information.
#---
class CustomersController < ApplicationController
  include TwitterUtil

  def index
    @statuses = Status.order("created_at desc").limit(20)
  end

  def retweet
    Status.find(params[:id]).background.retweet
    redirect_to customers_path
  end
end

app/controllers/dashboard_controller.rb
#---
# Excerpted from "Deploying with JRuby",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material, 
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose. 
# Visit http://www.pragmaticprogrammer.com/titles/jkdepj for more book information.
#---
class DashboardController < ApplicationController
  def index
  end

end

app/helpers/application_helper.rb
#---
# Excerpted from "Deploying with JRuby",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material, 
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose. 
# Visit http://www.pragmaticprogrammer.com/titles/jkdepj for more book information.
#---
module ApplicationHelper
  include TorqueBox::Injectors

  def stomp_url
    inject "stomp-endpoint"
  end
end

app/views/company/index.html.erb
<div>
  <%= form_tag(company_status_path, :method => :post) do %>
      <%= text_field_tag :status_text, "", :placeholder => "What is @#{@username} up to?", :size => 80 %>
      <%= submit_tag "Post" %>
  <% end %>
</div>
<div>
  <table>
    <tr>
      <th>Date</th>
      <th>Status</th>
    </tr>
    <% for s in @statuses %>
        <tr>
          <td><%= s[:created_at].strftime("%I:%M %p %d/%m/%Y") %></td>
          <td><%= s[:status_text] %></td>
        </tr>
    <% end %>
    <% if @statuses.empty? %>
        <tr>
          <td colspan="2">No updates</td>
        </tr>
    <% end %>
  </table>
</div>

app/views/customers/index.html.erb
<% content_for :head do %>
  <script type="text/javascript">
    var stompUrl = "<%= stomp_url %>";
  </script>
<% end %>
<div>
  <table id="statusTable">
    <thead>
        <tr>
          <th>User</th>
          <th>Date</th>
          <th></th>
          <th>Status</th>
        </tr>
    </thead>
    <tbody>
    <% for s in @statuses %>
        <tr>
          <td>@<%= s[:creator] %></td>
          <td><%= s[:created_at].strftime("%I:%M %p %d/%m/%Y") %></td>
          <td><%= link_to "Retweet", retweet_path(s), :method => :post %></td>
          <td><%= s[:status_text] %></td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/dashboard/index.html.erb
<p>
  Welcome to Twitalytics!
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitalytics</title>
  <%= stylesheet_link_tag "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.8/themes/ui-lightness/jquery-ui.css" %>  
  <%= javascript_include_tag "jquery", "rails" %>
  <%= csrf_meta_tags %>
  <%= yield :head %>
  <%= javascript_include_tag "/stilts-stomp.js" %>
  <style type="text/css">    
    html {
      margin: 5px 10px 10px 25px;
    }

    body {
      background-color: #3B4458;
      font-family: helvetica;
    }

    h1 {
       color: #fff;
    }

    p {
      font-style: italic;
      color: #fff;
    }

    a, a:visited {
      color: #92BADB;      
    }

    a:hover {
      color: #fff;
      background-color: #3B4458;
    }

    ul {
      list-style-type: square;
      color: #92BADB;
    }

    th {
      font: bold 11px "Trebuchet MS", Verdana, Arial, Helvetica, sans-serif;
      color: #6D929B;
      border-right: 1px solid #C1DAD7;
      border-bottom: 1px solid #C1DAD7;
      border-top: 1px solid #C1DAD7;
      letter-spacing: 2px;
      text-transform: uppercase;
      text-align: left;
      padding: 6px 6px 6px 12px;
      background: #CAE8EA;
    }

    td {
      font-size: 10pt;
      border-right: 1px solid #C1DAD7;
      border-bottom: 1px solid #C1DAD7;
      background: #fff;
      padding: 6px 6px 6px 12px;
      color: #6D929B;
    }


  </style>
</head>
<body>

<h1>Twitalytics</h1>
<% flash.each do |key, msg| %>
    <div class="flash <%= key %>"><%= msg %></div>
<% end %>
<div id="tabs">
  <ul>
    <li><%= link_to "Home", root_path %></li>
    <li><%= link_to "Company", company_path %></li>
    <li><%= link_to "Customers", customers_path %></li>
    <li><a href="#">Analysis</a></li>
  </ul>
  <div id="content">
    <%= yield %>
  </div>
</div>


</body>
</html>